### ISSUE TITLE
How i can send data over tx function

### ISSUE THREAD

**Issue by vilo93** [zerynth/lib-blockchain-ethereum#2]
i used in the config.py these contract Methods:
CONTRACT_METHODS = {
“setLed”: {
“args”: (),
“gas_limit”: “0x6691b7”,
},
“readLed”: {
“args”: (),
“gas_limit”: “0x6691b7”,
},
}
and i used this code to manipulate the value in setLed
tx_hash = game.tx(‘setLed’, nonce, value=(50,ethereum.WEI), args=(1,int))

in this smart-contract function (it works fine):
function setLed(int newOn) public payable {
on=newOn;
balance += msg.value;
}
The Problem is, there ist an IndexError shown in Zerynth-Studio raised at line 465 of blockchain.ethereum.ethereum._build_transaction

Can you help me to solve this Problem?

**Comment by zerynth** [comment]
Hello @vilo93,

at first glance, I think you need to add the argument type "int" for setLed in CONTRACT_METHODS and when calling game.tx just set args=(1,)

Let us know if it works,

**Comment by vilo93** [comment]
thank you for your quick response.
how can i add the argument type "int" in setLed? I can not register the function

**Comment by vilo93** [comment]
if i do this:
CONTRACT_METHODS = {
    "setLed": {
        "args": ("int"),
        "gas_limit": "0x6691b7",
    },
    "readLed": {
        "args": (),
        "gas_limit": "0x6691b7",
    },
}
i get an error:
UnsupportedError  at line 447 of blockchain.ethereum.ethereum.register_function

**Comment by zerynth** [comment]
Solidity types should be used. The size of the integer is needed going from 8 to 256 in 8 bits steps. I think that for a led, "int8" should be ok.

**Comment by vilo93** [comment]
yes i think "int8" would be ok too, but it does not work. Same error:
raised at line 447 of blockchain.ethereum.ethereum.register_function

i dont understand the error, because in ethereum.py are these supportet types in the code:
_supported_types = (
    'address',
    ('uint',_in_uint_range),
    ('int',_in_int_range),
    ('bytes', _in_bytes_range)
)
thank you in advance

**Comment by zerynth** [comment]
the "args" in CONTRACT_METHODS must be a tuple. The correct syntax is
`CONTRACT_METHODS = {
"setLed": {
"args": ("int8",),
"gas_limit": "0x6691b7",
},
"readLed": {
"args": (),
"gas_limit": "0x6691b7",
},
}`
Note the additional comma after int8

**Comment by vilo93** [comment]
yes, now its working fine!
thanks a lot!


for other people who have the same problem:

config.py:
CONTRACT_METHODS = { "setLed": { "args": ("int8",), "gas_limit": "0x6691b7", }, "readLed": { "args": (), "gas_limit": "0x6691b7", }, }

main.py
 tx_hash = game.tx('setLed', nonce, value=(50,ethereum.WEI), args=(1,))
and
smart contract in solidity:
    function setLed(int8 newOn) public payable {
        on=newOn;
        balance += msg.value;
    }

have fun :)
